#alt+d
@startuml messageFlow


title
使用者輸入流程
end title

start
:使用者輸入;
if (字串為數字) then
    if (快取沒值否？) is (無) then
        :詢問項目名稱;
    else (有)
        :詢問是否要重新記帳;
    endif    
    
:請輸入數字記帳或選取單;    
elseif (符合項目正則)
:詢問;
elseif (符合類型正則)
elseif (符合付款方式正則)
    if (現金) is (是) then

    elseif (卡片)
        :選擇卡片btn;
        if (符合卡片名稱正則)
        elseif (符合新增卡片正則)
        elseif (符合卡片類型正則)
        elseif (符合下一頁)
        endif
    elseif (電子票證)
        :選擇電子票證btn;
        if (符合電子票證名稱正則)
        elseif (符合新增電子票證正則)
        elseif (符合下一頁)
        endif
    endif
endif 


stop

@enduml